### ISSUE TITLE
setW

### ISSUE THREAD

**Issue by rjhilgefort** [anthonyjoeseph/spectacles-ts#35]
### Current Behavior

set doesn't allow for widening

### Desired Behavior

`setW`

### Suggested Solution

🤷 🙁 

### Who does this impact? Who is this for?

Practical use of the library. Common to need to widen like `modifyW`

### Describe alternatives you've considered

`optics-ts`, `monocle-ts`

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| spectacles-ts      | 1.0.7 |
| fp-ts      | 2.12.1 |
| TypeScript | 4.6.4 |

**Comment by anthonyjoeseph** [comment]
Thanks for using the library!

I had thought that `upsert` covered most, if not all, of the use cases for a `setW`. Could you give an example of something you'd like to be able to do?

**Comment by rjhilgefort** [comment]
`upsert` works well! I guess I just expected a widening version of `set` and didn't properly look through the docs. Thanks for the amazing library! I've tried all of em for TS and wished there was something as ergonomic as `partial-lenses`. This is by far the most practical of all the TS options!

**Comment by anthonyjoeseph** [comment]
Thanks for your kind words, glad it's working out!
